header: |
  made by Eric H.
                _____            _     _                         _
               |  __ \          | |   | |                       | |
   _____      _| |  | | __ _ ___| |__ | |__   ___   __ _ _ __ __| |
  / __\ \ /\ / / |  | |/ _` / __| '_ \| '_ \ / _ \ / _` | '__/ _` |
  \__ \\ V  V /| |__| | (_| \__ \ | | | |_) | (_) | (_| | | | (_| |
  |___/ \_/\_/ |_____/ \__,_|___/_| |_|_.__/ \___/ \__,_|_|  \__,_|

paths:
  - dev-ops/common/actions
templates:
  - source: "dev-ops/common/templates/.env.dist"
    destination: ".env"

const:
  APP_NAME: Shopware Dashboard
  APP_DEBUG: true
  APP_URL: http://localhost

  LOG_CHANNEL: stack

  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: ""

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: null

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET:

  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: mt1

environments:
  dev:
    templates:
      - source: "dev-ops/dev/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/dev/actions"

  cache:
    paths:
      - "dev-ops/cache/actions"
