header: |
  made by Eric H.
                _____            _     _                         _
               |  __ \          | |   | |                       | |
   _____      _| |  | | __ _ ___| |__ | |__   ___   __ _ _ __ __| |
  / __\ \ /\ / / |  | |/ _` / __| '_ \| '_ \ / _ \ / _` | '__/ _` |
  \__ \\ V  V /| |__| | (_| \__ \ | | | |_) | (_) | (_| | | | (_| |
  |___/ \_/\_/ |_____/ \__,_|___/_| |_|_.__/ \___/ \__,_|_|  \__,_|

paths:
  - dev-ops/common/actions
templates:
  - source: "dev-ops/common/templates/.env.dist"
    destination: ".env"

const:
  APP_NAME: swDashboard
  APP_DEBUG: true
  APP_URL: http://localhost

environments:
  dev:
    templates:
      - source: "dev-ops/dev/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/dev/actions"

  cache:
    paths:
      - "dev-ops/cache/actions"

  github:
    templates:
      - source: "dev-ops/github/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/github/actions"
